// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrlShortener.DataProvider;

#nullable disable

namespace UrlShortener.DataProvider.Migrations
{
    [DbContext(typeof(UrlShortenerContext))]
    [Migration("20220213201312_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("UrlShortener.DataProvider.Entities.HashingSpaceItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("RangeEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RangeStart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RangeStart", "RangeEnd");

                    b.ToTable("HashingSpace");
                });

            modelBuilder.Entity("UrlShortener.DataProvider.Entities.ShortenedUrl", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Shortened")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Shortened")
                        .IsUnique();

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("ShortenedUrls");
                });

            modelBuilder.Entity("UrlShortener.DataProvider.Entities.ShortenedUrlAnalytics", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasColumnType("TEXT");

                    b.Property<long>("ShortenedUrlId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("ShortenedUrlId");

                    b.ToTable("ShortenedUrlAnalytics");
                });

            modelBuilder.Entity("UrlShortener.DataProvider.Entities.ShortenedUrlAnalytics", b =>
                {
                    b.HasOne("UrlShortener.DataProvider.Entities.ShortenedUrl", "ShortenedUrl")
                        .WithMany()
                        .HasForeignKey("ShortenedUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShortenedUrl");
                });
#pragma warning restore 612, 618
        }
    }
}
